name: Build and Deploy

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-and-deploy:
    -name: Build and deploy Gatsby site
     runs-on: ubuntu-latest

    steps:

      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.0'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Copy to Ubuntu Server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'mycode'
          remote: '/home/azureuser/'
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SERVER_SSH_KEY}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: echo "remove the files"
          post_upload: sudo mv mycode/* /var/www/html/
